[buildPlans.Dyve]
family = "Dyve"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.Dyve.variants.design]
one = "no-base"
two = "curly-neck-serifed"
three = "flat-top-serifed"
four = "semi-open-serifless"
five = "upright-flat-serifed"
six = "straight-bar"
seven = "straight-serifed"
eight = "two-circles"
nine = "straight-bar"
zero = "slashed"
capital-a = "straight-top-serifed"
capital-b = "standard-unilateral-serifed"
capital-c = "unilateral-inward-serifed"
capital-d = "standard-unilateral-serifed"
capital-e = "top-left-serifed"
capital-f = "top-left-serifed"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "top-left-serifed"
capital-i = "short-serifed"
capital-j = "flat-hook-serifed"
capital-k = "symmetric-connected-top-left-serifed"
capital-l = "motion-serifed"
capital-m = "hanging-motion-serifed"
capital-n = "asymmetric-motion-serifed"
capital-p = "closed-motion-serifed"
capital-q = "crossing"
capital-r = "straight-top-left-serifed"
capital-s = "unilateral-inward-serifed"
capital-t = "motion-serifed"
capital-u = "toothless-corner-unilateral-motion-serifed"
capital-v = "straight-motion-serifed"
capital-w = "straight-vertical-sides-motion-serifed"
capital-x = "straight-unilateral-motion-serifed"
capital-y = "straight-motion-serifed"
capital-z = "straight-top-serifed"
a = "double-storey-hook-inward-serifed-toothless-corner"
b = "toothless-corner-serifless"
c = "unilateral-inward-serifed"
d = "toothless-corner-serifless"
e = "flat-crossbar"
f = "flat-hook-serifless-crossbar-at-x-height"
g = "single-storey-flat-hook-earless-corner"
h = "straight-serifless"
i = "hooky"
j = "flat-hook-serifed"
k = "symmetric-connected-serifless"
l = "hooky"
m = "earless-single-arch-short-leg-serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
r = "earless-corner-serifless"
s = "unilateral-inward-serifed"
t = "flat-hook"
u = "toothless-corner-serifless"
v = "straight-serifless"
w = "straight-vertical-sides-serifless"
x = "straight-serifless"
y = "straight-serifless"
z = "straight-top-serifed"
capital-eszet = "corner-bottom-serifed"
long-s = "flat-hook-tailed-middle-serifed"
eszet = "sulzbacher-bottom-serifed"
lower-eth = "straight-bar"
capital-thorn = "motion-serifed"
lower-thorn = "motion-serifed"
lower-alpha = "barred-top-cut-serifed"
lower-beta = "standard"
capital-gamma = "top-right-serifed"
lower-gamma = "straight"
capital-delta = "straight"
lower-delta = "flat-top"
lower-iota = "tailed-serifed"
capital-lambda = "straight-top-serifed"
lower-lambda = "straight-turn"
lower-mu = "toothed-bottom-right-serifed"
lower-nu = "straight"
lower-xi = "flat-top"
lower-pi = "tailless"
lower-tau = "flat-tailed"
lower-upsilon = "straight-serifed"
lower-phi = "neo-hellenic"
lower-chi = "straight-bilateral-motion-serifed"
lower-psi = "serifed"
cyrl-a = "double-storey-hook-inward-serifed-toothless-rounded"
cyrl-ve = "standard-unilateral-serifed"
cyrl-capital-zhe = "symmetric-touching"
cyrl-zhe = "symmetric-connected"
cyrl-capital-ze = "unilateral-inward-serifed"
cyrl-ze = "unilateral-serifed"
cyrl-capital-ka = "symmetric-connected-top-left-serifed"
cyrl-ka = "symmetric-connected-top-left-serifed"
cyrl-el = "straight"
cyrl-em = "hanging-motion-serifed"
cyrl-capital-en = "top-left-serifed"
cyrl-en = "top-left-serifed"
cyrl-capital-er = "closed-motion-serifed"
cyrl-er = "earless-corner-serifed"
cyrl-capital-u = "straight-motion-serifed"
cyrl-u = "straight-motion-serifed"
cyrl-ef = "top-serifed"
cyrl-che = "tailed"
cyrl-yeri = "corner"
cyrl-yery = "corner-tailed"
cyrl-capital-e = "unilateral-serifed"
cyrl-e = "unilateral-serifed"
cyrl-capital-ya = "curly-motion-serifed"
cyrl-ya = "straight-motion-serifed"
tittle = "round"
diacritic-dot = "round"
punctuation-dot = "round"
braille-dot = "round"
tilde = "low"
asterisk = "hex-low"
underscore = "low"
caret = "medium"
ascii-grave = "raised-turn-comma"
ascii-single-quote = "raised-comma"
paren = "flat-arc"
brace = "straight"
guillemet = "straight"
number-sign = "upright"
ampersand = "upper-open"
at = "fourfold"
dollar = "slanted-open"
cent = "slanted-open-cap"
percent = "rings-continuous-slash-also-connected"
bar = "natural-slope"
question = "corner-flat-hooked"
pilcrow = "high"
partial-derivative = "straight-bar"
micro-sign = "toothless-corner-motion-serifed"
decorative-angle-brackets = "middle"
lig-ltgteq = "flat"
lig-neq = "vertical-dotted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.Dyve.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.Dyve.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Dyve.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Dyve.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.Dyve.widths.SemiCondensed]
shape = 548
menu = 4
css = "semi-condensed"

[buildPlans.Dyve.widths.SemiExtended]
shape = 658
menu = 6
css = "semi-expanded"

[buildPlans.Dyve.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"