name: Build Iosevka Font

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      font_version:
        description: 'Iosevka Version'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install required packages
      run: |
        sudo apt update
        sudo apt install -y ttfautohint fontforge python3-fontforge
        sudo apt upgrade

    - name: Build font
      run: |
        npm install
        npm run build -- ttf::Dyve

    - name: Download font patcher
      run: |
        curl -L https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FontPatcher.zip --output FontPatcher.zip
        unzip FontPatcher.zip -d nerd-fonts

    - name: Patch fonts with Nerd Fonts
      run: |
        mkdir -p patched-fonts
        for font in dist/SpacesOne/TTF/*.ttf; do
          echo "Patching $font"
          fontforge -script ./nerd-fonts/font-patcher \
            --complete \
            --careful \
            --progressbars \
            --outputdir "patched-fonts" \
            "$font"
        done
      
    - name: Upload original fonts
      uses: actions/upload-artifact@v4
      with:
        name: Dyve-fonts-original
        path: dist/Dyve
        retention-days: 7

    - name: Upload patched fonts
      uses: actions/upload-artifact@v4
      with:
        name: Dyve-fonts-nerd
        path: patched-fonts
        retention-days: 7
